apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: ellamma-ecommerce
data:
  REDIS_HOST: "{{ .Values.configMap.REDIS_HOST }}"
  CATALOGUE_HOST: "{{ .Values.configMap.CATALOGUE_HOST }}"
  CATALOGUE_PORT: "8080"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: ellamma-ecommerce
  labels:
    project: ecommerce-project
    component: cart
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: ecommerce-project
      component: cart
      tier: backend
  template:
    metadata:
      labels:
        project: ecommerce-project
        component: cart
        tier: backend
    spec:
      containers:
      - name: cart
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart-config
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: ellamma-ecommerce
spec:
  selector:
    project: ecommerce-project
    component: cart
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }} #service Port
      targetPort: 8080 #container Port

